
version: "3.7"

services:
  commercetools-stripe-notification-module:
    build:
      context: .
      args:
        - NPM_USERNAME=${NPM_USERNAME}
        - NPM_PASSWORD=${NPM_PASSWORD}
        - NPM_EMAIL=${NPM_EMAIL}
    restart: always
    environment:
      - 'STRIPE_INTEGRATION_CONFIG=${STRIPE_INTEGRATION_CONFIG}'
      - PORT=${PORT:-8081}
    ports:
      - ${PORT:-8081}:${PORT:-8081}
